# Generated by Django 5.1.1 on 2026-05-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_card_due',
            field=models.IntegerField(default=0),
        ),
    ]
